services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.12-ubuntu2204
    container_name: mongo_db
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0"]

  mongo-setup:
    image: mongodb/mongodb-community-server:7.0.12-ubuntu2204
    volumes:
      - ./init-mongo.sh:/init-mongo.sh
    depends_on:
      - mongodb
    entrypoint: ["/bin/bash", "/init-mongo.sh"]

  redis:
    image: redis/redis-stack:7.4.0-v1-x86_64
    container_name: redis_db
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
      - "8001:8001"  

volumes:
  mongo_data:
  mongo_data_replica:
  redis_data:
